apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-tpw6
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0002-tenant/tkrw-pr712-0075-0002-app/devfile-sample-tpw6@sha256:20270ab791942de2c8a6a95be5d9b59236ce280604bafd57151dcfbffdcda5db
        name: my-nodejs
        resources: {}
status: {}
